name: proyecto_m4
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-233.0.dev <4.0.0'

dependencies:
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  form_validator: ^2.1.1
  go_router: ^8.0.1
  intl: ^0.18.1
  path: ^1.8.0
  image_picker: ^0.8.9
  google_sign_in: ^6.1.4
  social_login_buttons: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
