// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  ///
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  ///
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0_jHPB2BF4JfLZ_mUTyYk6zBtaM1_EQw',
    appId: '1:593258599790:web:b74210cc7000b6cc099d7f',
    messagingSenderId: '593258599790',
    projectId: 'forestal-m4',
    authDomain: 'forestal-m4.firebaseapp.com',
    storageBucket: 'forestal-m4.appspot.com',
    measurementId: 'G-DCFC7S9M8C',
  );

  ///
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXu7aqPXLsYcgvfX8eq064u-hpijPn9XQ',
    appId: '1:593258599790:android:58e0e08dd859bf91099d7f',
    messagingSenderId: '593258599790',
    projectId: 'forestal-m4',
    storageBucket: 'forestal-m4.appspot.com',
  );

 ///
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFWuVaJbgQsfqHVvqz0hGtH1p_P6LhDTg',
    appId: '1:593258599790:ios:c784fed383271c98099d7f',
    messagingSenderId: '593258599790',
    projectId: 'forestal-m4',
    storageBucket: 'forestal-m4.appspot.com',
    iosClientId: '593258599790-9u0ftacgmodqerfec9t31a4c3cqogd6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoM4',
  );
}
